### ISSUE TITLE
Linux: App Crashes after signin on Linux Mint

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/wp-desktop#106]
Shortly after logging in to the app on Linux Mint 17.3 the following error pops up:
```
Please restart the app and try again.

If you continue to have issues, please contact us and mention the error details below:

TypeError: this.platform.showNotificationsBadge is not a function
    at Platform.showNotificationsBadge (/usr/share/wpcom/resources/app/desktop.js:2360:18)
    at updateNotificationBadge (/usr/share/wpcom/resources/app/desktop.js:78584:13)
    at EventEmitter.<anonymous> (/usr/share/wpcom/resources/app/desktop.js:78595:4)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/usr/share/wpcom/resources/atom.asar/browser/api/lib/web-contents.js:120:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

![screenshot_26-02-2016-18 29 07](https://cloud.githubusercontent.com/assets/150348/13370230/d95a4eb2-dcb6-11e5-9cd7-cf6fb67485d7.png)

This has also been reported in 2552777-t  to occur in Linux Mint 17.1 

Restarting the app does not clear things up.

**Comment by MirkoHochmuth** [comment]
changing 'notification-badge' to 'false' in [home]/.config/WordPress.com/settings.json seems to solve the issue ...

**Comment by mkaz** [comment]
Duplicate #85 - fix is in place for next release
