### ISSUE TITLE
Network error crashes app on startup

### ISSUE THREAD

**Issue by beaucollins** [Automattic/wp-desktop#122]
App is crashing for user during launch and alerts with this error:

```
Error: socket hang up
at createHangUpError (_http_client.js:209:15)
at TLSSocket.socketCloseListener (_http_client.js:241:23)
at emitOne (events.js:82:20)
at TLSSocket.emit (events.js:169:7)
at TCP._onclose (net.js:469:12)
```

**Comment by beaucollins** [comment]
First hunch is the autoupdate since that seems to be the only thing that makes a network request during launch from the main node process.

**Comment by samjhamdy** [comment]
User is on Windows 10 platform.

User ticket: https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=2587406
