### ISSUE TITLE
Error: ENOENT: no such file or directory error on Mac

### ISSUE THREAD

**Issue by simplysaru** [Automattic/wp-desktop#211]
A user contacted me on chat earlier with the following error message. 

`Error: ENOENT: no such file or directory, open '/Users/USERNAME/Library/Application Support/WordPress.com/settings.json'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.writeFileSync (fs.js:1337:33)
    at createSettingsFile (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:53707:6)
    at Object.module.exports.load (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:53723:4)
    at Settings._getAll (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:12335:33)
    at Settings.isDebug (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:12342:19)
    at Object.<anonymous> (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:142933:15)
    at __webpack_require__ (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:21:30)
System info: {"platform":"darwin","release":"14.5.0","version":"1.3.5","build":"release"}`

**Comment by johngodley** [comment]
Confirm this happens for me when I delete `~/Library/Application Support/WordPress.com` and start the app
