### ISSUE TITLE
App never gets past loading screen

### ISSUE THREAD

**Issue by kwonye** [Automattic/wp-desktop#214]
Never gets past this screen. Quitting shows the following error message:

```
TypeError: Cannot read property 'startsWith' of null
    at isValidLastLocation (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:121916:11)
    at BrowserWindow.<anonymous> (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:121887:8)
    at emitOne (events.js:82:20)
    at BrowserWindow.emit (events.js:169:7)
    at menuItems.click (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:121022:9)
    at MenuItem.click (/Applications/WordPress.com.app/Contents/Resources/atom.asar/browser/api/lib/menu-item.js:69:18)
    at Function.delegate.executeCommand (/Applications/WordPress.com.app/Contents/Resources/atom.asar/browser/api/lib/menu.js:128:69)

System info: {"platform":"darwin","release":"15.6.0","version":"1.3.4","build":"release"}
```

<img width="1680" alt="screen shot 2016-07-28 at 11 27 37 am" src="https://cloud.githubusercontent.com/assets/1158819/17220773/5a01da36-54b6-11e6-909d-e089bfe23660.png">

**Comment by sendhil** [comment]
@kwonye was this on an upgrade? fresh install?

**Comment by kwonye** [comment]
> was this on an upgrade? fresh install?

Definitely not a fresh install, but I don't think it was an upgrade as well. It just stopped working one day... I didn't immediately upgrade before this happened. Just one day it stopped working.

I'll go ahead and re-download/install as the logs are documented.
