### ISSUE TITLE
Blank On Right Mouse Click Windows 10, Desktop App

### ISSUE THREAD

**Issue by Nicholas-Leslie** [Automattic/wp-desktop#251]
The application goes blank If you try and copy and paste to It started with Version 1.8.0 on windows 10 have updated Version 2.0.0 release and only crashes copy and paste In visual works fine with HTML.

A few error messages as follows............

TypeError: Error processing argument at index 0, conversion failure from C:\Program Files (x86)\WordPress.com\resources\app\public_desktop\win10-tray-icon.ico
at TypeError (native)
at new WindowsPlatform (C:\Program Files (x86)\WordPress.com\resources\app\desktop.js:143816:15)
at Platform.setMainWindow (C:\Program Files (x86)\WordPress.com\resources\app\desktop.js:5558:20)
at showAppWindow (C:\Program Files (x86)\WordPress.com\resources\app\desktop.js:143995:12)
at C:\Program Files (x86)\WordPress.com\resources\app\desktop.js:144004:15
at Server. (C:\Program Files (x86)\WordPress.com\resources\app\desktop.js:144085:4)
at Server.g (events.js:286:16)
at emitNone (events.js:86:13)
at Server.emit (events.js:185:7)
at emitListeningNT (net.js:1279:10)
System info: {"platform":"win32","release":"10.0.14393","version":"1.9.0","build":"release"}
[OK]

.................................................

[Window Title]
Error

[Main Instruction]
WordPress.com ran into an error

[Content]
Please restart the app and try again.

If you continue to have issues, please contact us at help@wordpress.com and mention the error details below:

TypeError: Error processing argument at index 0, conversion failure from C:\Program Files (x86)\WordPress.com\resources\app\public_desktop\win7-tray-icon-notification.ico
    at TypeError (native)
    at WindowsPlatform.showNotificationsBadge (C:\Program Files (x86)\WordPress.com\resources\app\desktop.js:147990:13)
    at Platform.showNotificationsBadge (C:\Program Files (x86)\WordPress.com\resources\app\desktop.js:5466:18)
    at updateNotificationBadge (C:\Program Files (x86)\WordPress.com\resources\app\desktop.js:148480:13)
    at EventEmitter.<anonymous> (C:\Program Files (x86)\WordPress.com\resources\app\desktop.js:148491:4)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (C:\Program Files (x86)\WordPress.com\resources\electron.asar\browser\api\web-contents.js:209:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

System info: {"platform":"win32","release":"6.2.9200","version":"2.0.0","build":"release"}

[OK]

............................................................................

[Window Title]
Error

[Main Instruction]
WordPress.com ran into an error

[Content]
Please restart the app and try again.

If you continue to have issues, please contact us at help@wordpress.com and mention the error details below:

TypeError: Error processing argument at index 0, conversion failure from C:\Program Files (x86)\WordPress.com\resources\app\public_desktop\win7-tray-icon-notification.ico
    at TypeError (native)
    at WindowsPlatform.showNotificationsBadge (C:\Program Files (x86)\WordPress.com\resources\app\desktop.js:147990:13)
    at Platform.showNotificationsBadge (C:\Program Files (x86)\WordPress.com\resources\app\desktop.js:5466:18)
    at updateNotificationBadge (C:\Program Files (x86)\WordPress.com\resources\app\desktop.js:148480:13)
    at EventEmitter.<anonymous> (C:\Program Files (x86)\WordPress.com\resources\app\desktop.js:148491:4)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (C:\Program Files (x86)\WordPress.com\resources\electron.asar\browser\api\web-contents.js:209:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

System info: {"platform":"win32","release":"6.2.9200","version":"2.0.0","build":"release"}

[OK]

Settings applied to: WordPress.com:
User Account Control: Run as administrator my computer Is 64 bit x64-based processor, 12GB Ram running windows 10 Pro

**Comment by rachelmcr** [comment]
Thank you reporting this! I noticed you also reported this issue in a comment here:

https://github.com/Automattic/wp-desktop/issues/241

I'm going to close this issue in favor of that one, since we're tracking the right-click issue there. If this also happens when you copy and paste in other ways (e.g. with keyboard commands) please let us know.
