### ISSUE TITLE
OSX Test Target Does Not Work

### ISSUE THREAD

**Issue by astralbodies** [Automattic/wp-desktop#281]
As discussed in #275 when performing a `make test-osx` causes an exception to be displayed:

```Downloading spellchecker-darwin-v3.2.3-electron-v0.36.8.zip
Packaging app for platform darwin x64 using electron v1.3.5

Optimizing the Mac OS X build at /Users/aaron/src/wp-desktop/release/WordPress.com-darwin-x64/WordPress.com.app
 - Renaming helper plist files
 - Removing default app
 - Signing app
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './release/WordPress.com-darwin-x64/WordPress.com.app/Contents/Resources/app.asar'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.exports.readArchiveHeaderSync (/Users/aaron/src/wp-desktop/node_modules/asar/lib/disk.js:79:13)
    at Object.module.exports.readFilesystemSync (/Users/aaron/src/wp-desktop/node_modules/asar/lib/disk.js:105:21)
    at Object.module.exports.extractAll (/Users/aaron/src/wp-desktop/node_modules/asar/lib/asar.js:186:23)
    at Command.<anonymous> (/Users/aaron/src/wp-desktop/node_modules/asar/bin/asar:59:15)
    at Command.listener (/Users/aaron/src/wp-desktop/node_modules/asar/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/Users/aaron/src/wp-desktop/node_modules/asar/node_modules/commander/index.js:615:12)
make: *** [test-osx] Error 1
aaron@astralimac [07:52:04] [~/src/wp-desktop] [try/ssr-config-compat]
-> % 
```

Per @johngodley:

> It doesnt appear to be copying the app to the test directory. adding that to the Makefile with `cp -R ./release/WordPress.com-darwin-x64/WordPress.com.app/Contents/Resources/ ./release/WordPress.com-darwin-x64-unpacked/desktop` fixes the error, but it then complains about no `boot` function
> so the app itself doesnt appear to be exporting a function that can be used to test with
> the idea of the test is that the entry point is called here - https://github.com/Automattic/wp-desktop/blob/master/desktop/app.js - and then `finished_cb` is called, which is then inspected inside the unit test to make sure that everything started as expected. this was based on what was available in 2015 so there may be a much easier way of doing it now

**Comment by spen** [comment]
I'm actually seeing a different error when running `make test-osx`:

```bash
ptimizing the Mac OS X build at /Users/Spen/Projects/automattic/wp-desktop/release/WordPress.com-darwin-x64/WordPress.com.app
 - Renaming helper plist files
 - Removing default app
 - Signing app
{ Error: Cannot find module '../../release/WordPress.com-darwin-x64-unpacked/desktop/app'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/Users/Spen/Projects/automattic/wp-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Spen/Projects/automattic/wp-desktop/resource/test/osx.js:12:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/Spen/Projects/automattic/wp-desktop/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/Spen/Projects/automattic/wp-desktop/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/Spen/Projects/automattic/wp-desktop/node_modules/mocha/lib/mocha.js:469:10)
    at Object.run (/Users/Spen/Projects/automattic/wp-desktop/release/WordPress.com-darwin-x64-unpacked/node_modules/electron-mocha/mocha.js:65:28)
    at App.app.on (/Users/Spen/Projects/automattic/wp-desktop/release/WordPress.com-darwin-x64-unpacked/node_modules/electron-mocha/index.js:36:11)
    at emitOne (events.js:101:20)
    at App.emit (events.js:188:7) code: 'MODULE_NOT_FOUND' }
Error: Cannot find module '../../release/WordPress.com-darwin-x64-unpacked/desktop/app'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/Users/Spen/Projects/automattic/wp-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Spen/Projects/automattic/wp-desktop/resource/test/osx.js:12:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/Spen/Projects/automattic/wp-desktop/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/Spen/Projects/automattic/wp-desktop/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/Spen/Projects/automattic/wp-desktop/node_modules/mocha/lib/mocha.js:469:10)
    at Object.run (/Users/Spen/Projects/automattic/wp-desktop/release/WordPress.com-darwin-x64-unpacked/node_modules/electron-mocha/mocha.js:65:28)
    at App.app.on (/Users/Spen/Projects/automattic/wp-desktop/release/WordPress.com-darwin-x64-unpacked/node_modules/electron-mocha/index.js:36:11)
    at emitOne (events.js:101:20)
    at App.emit (events.js:188:7)
make: *** [test-osx] Error 1
```

I'm going to take a look at this today in the context of the desktop > Calypso merge but also `wp-desktop` :)

**Comment by spen** [comment]
From what I can see here, it seems that the `make osx-test` target is no longer relevant - or at least needs some serious reconsideration in approach.
It seems we're aiming to test `desktop/app.js`, that it runs calls `finished_cb` as @johngodley mentions.
The reason I say that this may no longer be relevant is that `app.js` is now bundled with Webpack... the entry point being `desktop/index.js`.

The error that @astralbodies shows above is interesting and is what I see when running `make test-osx` in the branch under https://github.com/Automattic/wp-calypso/pull/12430.
It's interesting in that the app isn't packaged as a `.asar` at all - even within the release:
<img width="461" alt="screen shot 2017-04-13 at 12 19 29" src="https://cloud.githubusercontent.com/assets/4335450/25002672/8cb8c15c-2043-11e7-8408-3943ead68126.png">

This is why the `asar e ...` (extract) command throws the reported error.
Since we don't produce a `.asar` the app is essentially already 'unpacked' and so we should be able to skip this extraction step and look directly at the app, something like this:

```make
test-osx: osx
	@mkdir -p ./release/WordPress.com-darwin-x64/node_modules/electron-mocha
	@cp -R ./node_modules/electron-mocha ./release/WordPress.com-darwin-x64/node_modules/
	@NODE_PATH=./release/WordPress.com-darwin-x64-unpackaged/node_modules ELECTRON_PATH=$(NPM_BIN)/electron ./release/WordPress.com-darwin-x64/node_modules/electron-mocha/bin/electron-mocha --inline-diffs --timeout 5000 ./resource/test/osx.js
```

But this brings me back to the starting point of this comment - `app` gets bundled and so is no longer available in the resulting apps.

I think there are 2 takeaways here - that we should consider packaging with `asar` and that we should look for a different approach to the `osx` builds :)

**Comment by johngodley** [comment]
> I think there are 2 takeaways here - that we should consider packaging with asar (why?) and that we should look for a different approach to the osx builds :)

Everything used to be asar packed, but there was a change in Calypso that forced us to bundle the server code, and that stopped it working when packed (packing changes the paths yet again, and Calypso already does funny things in the server).

Packing with asar doesn't make a huge difference in terms of size or performance. However, the install directory is a lot cleaner as there's a single file rather than thousands. On Windows you can then run into problems with the number of files in a directory.

On a separate (and much smaller) Electron [project](https://github.com/Automattic/biab-installer/blob/master/package.json#L127-L166) I had a good experience with [Electron Builder](https://github.com/electron-userland/electron-builder). I think this would be an ideal replacement for the custom build code in the desktop app. Everything could be replaced with a simple config file and Electron Builder handles pretty much everything else.

**Comment by spen** [comment]
>  I had a good experience with Electron Builder.

I've not taken a solid look at or the other [userland](https://github.com/electron-userland) projects yet but that sounds promising :)
If it can help reduce some of the complexity in building for each platform that sounds like it could be a really nice win.

> ...but there was a change in Calypso that forced us to bundle the server code.

Since we're now bundling the server code, it's not possible to find and call the `app.js` within the packaged app.
So even if we were to remove the asar extraction step and refer directly to the pre-webpack `app.js` this wouldn't be representative of how the app runs...
Given that, I tried to test the bundled code... the issue being that instead of being able to call that bundle as a function with a callback all we can do is `require( ... )` it and allow it to run.
Unfortunately this means that we can't set up this listener during the test:

```js
mainWindow.webContents.on( 'did-finish-load', function() {
	mainWindow.webContents.send( 'is-calypso' );
} );
```

However, by adding `mainWindow.webContents.send( 'is-calypso' );` to the `did-finish-load` handler in [`desktop/server/index.js`](https://github.com/Automattic/wp-desktop/blob/master/desktop/server/index.js#L44) we can trigger the same event and get a green light on the following test body:

```js
// Listen...
ipcMain.on( 'is-calypso-response', function( ev, value ) {
	expect( value ).to.be.true;
	done();
} );

// requiring runs the app code, triggering the `is-calypso-response' event along the way.
require( '../../release/WordPress.com-darwin-x64/WordPress.com.app/Contents/Resources/app/desktop/desktop.js' );
```

I'm keen to hear what you think about this - particularly because I feel there was probabily good reason for not adding sending the `ipc` event in `server/index.js`s `'did-finish-load'` handler in the first place.

If it seems reasonable I'll look at popping open a P :)

Note: I've been testing this in the desktop merge branch in Calypso so there may be caveats applying these changes in `wp-desktop` but I can't see them deviating too far.

**Comment by spen** [comment]
Here's what that solution looks like in the context of the desktop > Calypso merge:
https://github.com/Automattic/wp-calypso/pull/13295

**Comment by johngodley** [comment]
> I'm keen to hear what you think about this approach- particularly because I feel there was probably good reason for not adding sending the ipc event in server/index.jss 'did-finish-load' handler in the first place.

If it works, go for it!
