### ISSUE TITLE
OSX: App doesn't load - Cannot read property 'split' of undefined 

### ISSUE THREAD

**Issue by liviopv** [Automattic/wp-desktop#432]
The user is claiming the app doesn't open properly and it only shows the error below when they try to initiate it:

```
TypeError: Cannot read property 'split' of undefined 
at parseCookie (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:266633:24) 
at Array.map (native) 
at EventEmitter.<anonymous> (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:266671:18) 
at emitOne (events.js:96:13) 
at EventEmitter.emit (events.js:188:7) 
at ClientRequest.<anonymous> (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:266616:14) 
at Object.onceWrapper (events.js:290:19) 
at emitOne (events.js:96:13) 
at ClientRequest.emit (events.js:188:7) 
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)

System info: {"platform":"darwin","release":"13.3.0","version":"3.2.0","build":"release"}
```
I asked the to confirming Mac OS version and to try an uninstall/reinstall.

Reported on: 1050478-zen

**Comment by designsimply** [comment]
I searched for the "TypeError: Cannot read property 'split' of undefined" error in the `wp-calypso` project and found two mentions, both related to image galleries.

1. https://github.com/Automattic/wp-calypso/issues/13144 (closed due to inactivity)
2. https://github.com/Automattic/wp-calypso/issues/30518 (more specifically about gallery blocks)

@liviopv I am going to close this issue in favor of continuing at https://github.com/Automattic/wp-calypso/issues/30518 and leaving it up to you if you would like to loop back to 1050478-zen and check in with the user to see if they are still having trouble and if they are seeing the error message for any posts using galleries. If you check back in with the user, it would also be helpful to know a bit more about exactly when the error appears and if it blocks them from doing other things in the app such as viewing stats or notifications.
