### ISSUE TITLE
Crash at startup: this.platform.showNotificationsBadge is not a function

### ISSUE THREAD

**Issue by zinigor** [Automattic/wp-desktop#85]
I am running the latest deb from wordpress.com:
> ii  wordpress.com                                        1.2.7                                      amd64        WordPress.com  Desktop client

and I think I have the beta channel turned on, but I can't check because it won't start, it crashes on startup with the following message:

> TypeError: this.platform.showNotificationsBadge is not a function
    at Platform.showNotificationsBadge (/usr/share/wpcom/resources/app/desktop.js:2360:18)
    at updateNotificationBadge (/usr/share/wpcom/resources/app/desktop.js:78584:13)
    at EventEmitter.<anonymous> (/usr/share/wpcom/resources/app/desktop.js:78595:4)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/usr/share/wpcom/resources/atom.asar/browser/api/lib/web-contents.js:120:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

I seem to only have this when I have unread notifications. Happy to test more if you need something else.

**Comment by kristarella** [comment]
Two other reports of this from users via email so far.
